### ISSUE TITLE
Submission error / Exist DB error

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/majlis-data#106]
@wsalesky I could not submit changes I made to a file on manuForma to the Github repository. I investigated the webhook (everything good there). My next stop was the git-commit.xql in the majlis-data app on our server. I was surprised to see that the entire folder (services) containing that file had just vanished. 

This would explain the submission error, but it also poses the question what went on there and how we can prevent it in the future?

Also: should I just copy and adapt the services folder from manuForma app into majlis-data?

**Comment by wsalesky** [comment]
@mMoliere The git-commit.xql, lives in the manuForma app, not the majlis-data app, so that part is fine. I will do some investigating, but first can you take a look at the manuForma/services/git-commit.xql and make sure the $gitcommit:authorization-token is correct?
