### ISSUE TITLE
Changes submitted on manuForma don't arrive on Github

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/majlis-data#124]
@wsalesky While manuForma confirms that the changed file has been submitted, there is no pull request when I check the repository. A glance at the webhook configuration shows that there was a problem with changes to XML files that I submitted yesterday from my local computer. Could this be the cause?

**Comment by wsalesky** [comment]
@mMoliere Is it just that file that fails, or do all the files fail? If they are all failing, it is a bug, if it is just the one file, it is a problem with the file. Either way, we should open an issue on manuForma for better error reporting on git-commit.

**Comment by mMoliere** [comment]
@wsalesky That's a fair question. I tried it with 6 out of 12 files and they all failed. I will open an issue in the other repository.
