### ISSUE TITLE
Update Zotero Import 

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/majlis-data#133]
@wsalesky We have new entries in our Zotero DB that are not available in manuForma. This suggests to me that this is sofar a process that has to be manually iniated. 

Could you outline to me how it is done manually?

Is there a way to automate it?

**Comment by wsalesky** [comment]
@mMoliere You can update by going to the zotero2bibl part of the application:

**Comment by wsalesky** [comment]
@mMoliere Did you get this sorted out?

**Comment by mMoliere** [comment]
@wsalesky No, unfortunately not. I tried updating with several hours in between the steps and it still failed.

**Comment by mMoliere** [comment]
@wsalesky It always breaks when I reach 550
