### ISSUE TITLE
Webhook error

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/majlis-data#137]
@wsalesky The webhook is behaving strangely. I modified a bunch of files on my machine and created a pull request for them. They don't through to the server.

When I open the webhook menu, the error message looks like this:

![Screenshot 2023-10-24 at 22 47 33](https://github.com/majlis-erc/majlis-data/assets/73166992/19d980b9-a056-4f72-88ad-d3655818531b)

On the other hand, when I submit changes to a file from manuForma they get through to GitHub.

We are training some people tomorrow. It would be really great if we could show them the entire process.

**Comment by wsalesky** [comment]
@mMoliere I have a bunch of family related obligations for the next few hours, but I will look at it tonight and try to get it resolved. Thanks for your patience. (It is odd that there is no error message though. )

**Comment by mMoliere** [comment]
@wsalesky Yes of course, I don't want to keep you from your obligations. It is completely fine to look at it tonight.

**Comment by wsalesky** [comment]
@mMoliere Interesting. The webhooks were not firing due to the website security certificate. I have temporarily disabled the ssl verification for the webhooks and it is running fine now. Please double check to make sure it is working for you as well.

**Comment by mMoliere** [comment]
@wsalesky Thank you! That worked. I shall ask our admin about the certificate. I hope I did not spoil your family event.
